// refer to website
// https://gobyexample.com/json

package main

import (
	"encoding/json"
	"fmt"
)

type Response2 struct {
	Page   int      `json:"page"`
	Fruits []string `json:"fruits"`
}

// type Response struct {
// 	item1 []string
// 	item2 string
// }

// type Response1 struct[
// 	test []Response
// ]

type AutoGenerated struct {
	Columns []string        `json:"columns"`
	Data    [][]interface{} `json:"data"`
}

func main() {
	str := `{
		"page": 1,
		 "fruits": [["apple"], "peach"]
		}`
	res := Response2{}
	json.Unmarshal([]byte(str), &res)
	fmt.Println(res)
	fmt.Println(res.Fruits[0])

	strs := `{
		"columns" : [ "id(r)", "n1.name", "labels(n1)", "type(r)", "n2.name", "labels(n2)" ],
		"data" : [ [ 385, "testName3", [ "testTag3" ], "take", "testName", [ "testTag" ] ], [ 384, "testName", [ "testTag" ], "belong", "testName2", [ "testTag2" ] ], [ 386, "testName2", [ "testTag2" ], "follow", "testName3", [ "testTag3" ] ], [ 387, "testName", [ "testTag" ], "after", "testName3", [ "testTag3" ] ] ]
	}`

	// var f interface{}

	res2 := AutoGenerated{}
	json.Unmarshal([]byte(strs), &res2)
	// fmt.Println(m["columns"])
	// fmt.Println(reflect.TypeOf(m["data"]))
	fmt.Println(res2)
	// fmt.Println(f.data)

	fmt.Println(res2.Columns)
}
