// Code generated by protoc-gen-go.
// source: blockchain.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	blockchain.proto

It has these top-level messages:
	RemoveBlockRequest
	RemoveBlockResponse
	AddBlockRequest
	AddBlockResponse
	Block
	RemoveBlockchain
	GetBlockchainRequest
	GetBlockchainResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoveBlockRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *RemoveBlockRequest) Reset()                    { *m = RemoveBlockRequest{} }
func (m *RemoveBlockRequest) String() string            { return proto1.CompactTextString(m) }
func (*RemoveBlockRequest) ProtoMessage()               {}
func (*RemoveBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RemoveBlockRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RemoveBlockResponse struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *RemoveBlockResponse) Reset()                    { *m = RemoveBlockResponse{} }
func (m *RemoveBlockResponse) String() string            { return proto1.CompactTextString(m) }
func (*RemoveBlockResponse) ProtoMessage()               {}
func (*RemoveBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RemoveBlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type AddBlockRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *AddBlockRequest) Reset()                    { *m = AddBlockRequest{} }
func (m *AddBlockRequest) String() string            { return proto1.CompactTextString(m) }
func (*AddBlockRequest) ProtoMessage()               {}
func (*AddBlockRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddBlockRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AddBlockResponse struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *AddBlockResponse) Reset()                    { *m = AddBlockResponse{} }
func (m *AddBlockResponse) String() string            { return proto1.CompactTextString(m) }
func (*AddBlockResponse) ProtoMessage()               {}
func (*AddBlockResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddBlockResponse) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Block struct {
	PrevBlockHash string `protobuf:"bytes,1,opt,name=prevBlockHash" json:"prevBlockHash,omitempty"`
	Data          string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Hash          string `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto1.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RemoveBlockchain struct {
}

func (m *RemoveBlockchain) Reset()                    { *m = RemoveBlockchain{} }
func (m *RemoveBlockchain) String() string            { return proto1.CompactTextString(m) }
func (*RemoveBlockchain) ProtoMessage()               {}
func (*RemoveBlockchain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetBlockchainRequest struct {
}

func (m *GetBlockchainRequest) Reset()                    { *m = GetBlockchainRequest{} }
func (m *GetBlockchainRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetBlockchainRequest) ProtoMessage()               {}
func (*GetBlockchainRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type GetBlockchainResponse struct {
	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *GetBlockchainResponse) Reset()                    { *m = GetBlockchainResponse{} }
func (m *GetBlockchainResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetBlockchainResponse) ProtoMessage()               {}
func (*GetBlockchainResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetBlockchainResponse) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto1.RegisterType((*RemoveBlockRequest)(nil), "proto.RemoveBlockRequest")
	proto1.RegisterType((*RemoveBlockResponse)(nil), "proto.RemoveBlockResponse")
	proto1.RegisterType((*AddBlockRequest)(nil), "proto.AddBlockRequest")
	proto1.RegisterType((*AddBlockResponse)(nil), "proto.AddBlockResponse")
	proto1.RegisterType((*Block)(nil), "proto.Block")
	proto1.RegisterType((*RemoveBlockchain)(nil), "proto.RemoveBlockchain")
	proto1.RegisterType((*GetBlockchainRequest)(nil), "proto.GetBlockchainRequest")
	proto1.RegisterType((*GetBlockchainResponse)(nil), "proto.GetBlockchainResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Blockchain service

type BlockchainClient interface {
	AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error)
	GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error)
	RemoveBlockchain(ctx context.Context, in *RemoveBlockRequest, opts ...grpc.CallOption) (*RemoveBlockResponse, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error) {
	out := new(AddBlockResponse)
	err := grpc.Invoke(ctx, "/proto.Blockchain/AddBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error) {
	out := new(GetBlockchainResponse)
	err := grpc.Invoke(ctx, "/proto.Blockchain/GetBlockchain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) RemoveBlockchain(ctx context.Context, in *RemoveBlockRequest, opts ...grpc.CallOption) (*RemoveBlockResponse, error) {
	out := new(RemoveBlockResponse)
	err := grpc.Invoke(ctx, "/proto.Blockchain/RemoveBlockchain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blockchain service

type BlockchainServer interface {
	AddBlock(context.Context, *AddBlockRequest) (*AddBlockResponse, error)
	GetBlockchain(context.Context, *GetBlockchainRequest) (*GetBlockchainResponse, error)
	RemoveBlockchain(context.Context, *RemoveBlockRequest) (*RemoveBlockResponse, error)
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Blockchain/AddBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).AddBlock(ctx, req.(*AddBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetBlockchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlockchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Blockchain/GetBlockchain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlockchain(ctx, req.(*GetBlockchainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_RemoveBlockchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).RemoveBlockchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Blockchain/RemoveBlockchain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).RemoveBlockchain(ctx, req.(*RemoveBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlock",
			Handler:    _Blockchain_AddBlock_Handler,
		},
		{
			MethodName: "GetBlockchain",
			Handler:    _Blockchain_GetBlockchain_Handler,
		},
		{
			MethodName: "RemoveBlockchain",
			Handler:    _Blockchain_RemoveBlockchain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain.proto",
}

func init() { proto1.RegisterFile("blockchain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xca, 0xc9, 0x4f,
	0xce, 0x4e, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53,
	0x4a, 0x1a, 0x5c, 0x42, 0x41, 0xa9, 0xb9, 0xf9, 0x65, 0xa9, 0x4e, 0x20, 0x05, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x26, 0x97, 0x30, 0x8a, 0xca, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x90, 0xd2, 0x8c, 0xc4, 0xe2, 0x0c, 0x98, 0x52, 0x10, 0x5b, 0x49, 0x95, 0x8b, 0xdf, 0x31,
	0x25, 0x85, 0xa0, 0x89, 0x6a, 0x5c, 0x02, 0x08, 0x65, 0x78, 0x8c, 0x0b, 0xe5, 0x62, 0x05, 0x2b,
	0x12, 0x52, 0xe1, 0xe2, 0x2d, 0x28, 0x4a, 0x2d, 0x03, 0x73, 0x3c, 0x10, 0xaa, 0x50, 0x05, 0xe1,
	0x56, 0x31, 0x21, 0xac, 0x82, 0x1b, 0xcb, 0x8c, 0x64, 0xac, 0x10, 0x97, 0x00, 0x92, 0x87, 0xc0,
	0x61, 0xa3, 0x24, 0xc6, 0x25, 0xe2, 0x9e, 0x5a, 0x82, 0x10, 0x80, 0x3a, 0x5f, 0xc9, 0x96, 0x4b,
	0x14, 0x4d, 0x1c, 0xea, 0x5e, 0x15, 0x2e, 0x36, 0x70, 0xd0, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6b,
	0x70, 0x1b, 0xf1, 0x40, 0x82, 0x57, 0x0f, 0xe2, 0x2b, 0xa8, 0x9c, 0xd1, 0x33, 0x46, 0x2e, 0x2e,
	0x84, 0x66, 0x21, 0x5b, 0x2e, 0x0e, 0x98, 0xc7, 0x85, 0xc4, 0xa0, 0x1a, 0xd0, 0x02, 0x4c, 0x4a,
	0x1c, 0x43, 0x1c, 0x62, 0xa3, 0x12, 0x83, 0x90, 0x0f, 0x17, 0x2f, 0x8a, 0x63, 0x84, 0xa4, 0xa1,
	0x6a, 0xb1, 0x39, 0x5d, 0x4a, 0x06, 0xbb, 0x24, 0xdc, 0x34, 0x6f, 0xcc, 0x60, 0x10, 0x92, 0x84,
	0xea, 0xc1, 0x4c, 0x1a, 0x52, 0x52, 0xd8, 0xa4, 0x60, 0x86, 0x25, 0xb1, 0x81, 0x25, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x6a, 0xfc, 0x25, 0x70, 0x02, 0x00, 0x00,
}
