package disks

type NtnxDisks struct {
	Metadata struct {
		GrandTotalEntities int    `json:"grand_total_entities"`
		TotalEntities      int    `json:"total_entities"`
		FilterCriteria     string `json:"filter_criteria"`
		SortCriteria       string `json:"sort_criteria"`
		Page               int    `json:"page"`
		Count              int    `json:"count"`
		StartIndex         int    `json:"start_index"`
		EndIndex           int    `json:"end_index"`
	} `json:"metadata"`
	Entities []struct {
		ID                  string      `json:"id"`
		DiskUUID            string      `json:"disk_uuid"`
		ClusterUUID         string      `json:"cluster_uuid"`
		StorageTierName     string      `json:"storage_tier_name"`
		ServiceVmid         string      `json:"service_vmid"`
		NodeUUID            string      `json:"node_uuid"`
		LastServiceVmid     interface{} `json:"last_service_vmid"`
		LastNodeUUID        interface{} `json:"last_node_uuid"`
		HostName            string      `json:"host_name"`
		CvmIPAddress        string      `json:"cvm_ip_address"`
		MountPath           string      `json:"mount_path"`
		DiskSize            int64       `json:"disk_size"`
		MarkedForRemoval    bool        `json:"marked_for_removal"`
		DataMigrated        bool        `json:"data_migrated"`
		Online              bool        `json:"online"`
		DiskStatus          string      `json:"disk_status"`
		Location            int         `json:"location"`
		SelfEncryptingDrive bool        `json:"self_encrypting_drive"`
		DiskHardwareConfig  struct {
			SerialNumber           string      `json:"serial_number"`
			DiskID                 string      `json:"disk_id"`
			DiskUUID               string      `json:"disk_uuid"`
			Location               int         `json:"location"`
			Bad                    bool        `json:"bad"`
			Mounted                bool        `json:"mounted"`
			MountPath              string      `json:"mount_path"`
			Model                  string      `json:"model"`
			Vendor                 string      `json:"vendor"`
			BootDisk               bool        `json:"boot_disk"`
			OnlyBootDisk           bool        `json:"only_boot_disk"`
			UnderDiagnosis         bool        `json:"under_diagnosis"`
			BackgroundOperation    interface{} `json:"background_operation"`
			CurrentFirmwareVersion string      `json:"current_firmware_version"`
			TargetFirmwareVersion  string      `json:"target_firmware_version"`
			CanAddAsNewDisk        bool        `json:"can_add_as_new_disk"`
			CanAddAsOldDisk        bool        `json:"can_add_as_old_disk"`
		} `json:"disk_hardware_config"`
		DynamicRingChangingNode interface{} `json:"dynamic_ring_changing_node"`
		Stats                   struct {
			HypervisorAvgIoLatencyUsecs          string `json:"hypervisor_avg_io_latency_usecs"`
			NumReadIops                          string `json:"num_read_iops"`
			HypervisorWriteIoBandwidthKBps       string `json:"hypervisor_write_io_bandwidth_kBps"`
			TimespanUsecs                        string `json:"timespan_usecs"`
			ControllerNumReadIops                string `json:"controller_num_read_iops"`
			ReadIoPpm                            string `json:"read_io_ppm"`
			ControllerNumIops                    string `json:"controller_num_iops"`
			TotalReadIoTimeUsecs                 string `json:"total_read_io_time_usecs"`
			ControllerTotalReadIoTimeUsecs       string `json:"controller_total_read_io_time_usecs"`
			HypervisorNumIo                      string `json:"hypervisor_num_io"`
			ControllerTotalTransformedUsageBytes string `json:"controller_total_transformed_usage_bytes"`
			ControllerNumWriteIo                 string `json:"controller_num_write_io"`
			AvgReadIoLatencyUsecs                string `json:"avg_read_io_latency_usecs"`
			ControllerTotalIoTimeUsecs           string `json:"controller_total_io_time_usecs"`
			ControllerTotalReadIoSizeKbytes      string `json:"controller_total_read_io_size_kbytes"`
			ControllerNumSeqIo                   string `json:"controller_num_seq_io"`
			ControllerReadIoPpm                  string `json:"controller_read_io_ppm"`
			ControllerTotalIoSizeKbytes          string `json:"controller_total_io_size_kbytes"`
			ControllerNumIo                      string `json:"controller_num_io"`
			HypervisorAvgReadIoLatencyUsecs      string `json:"hypervisor_avg_read_io_latency_usecs"`
			NumWriteIops                         string `json:"num_write_iops"`
			ControllerNumRandomIo                string `json:"controller_num_random_io"`
			NumIops                              string `json:"num_iops"`
			HypervisorNumReadIo                  string `json:"hypervisor_num_read_io"`
			HypervisorTotalReadIoTimeUsecs       string `json:"hypervisor_total_read_io_time_usecs"`
			ControllerAvgIoLatencyUsecs          string `json:"controller_avg_io_latency_usecs"`
			NumIo                                string `json:"num_io"`
			ControllerNumReadIo                  string `json:"controller_num_read_io"`
			HypervisorNumWriteIo                 string `json:"hypervisor_num_write_io"`
			ControllerSeqIoPpm                   string `json:"controller_seq_io_ppm"`
			ControllerReadIoBandwidthKBps        string `json:"controller_read_io_bandwidth_kBps"`
			ControllerIoBandwidthKBps            string `json:"controller_io_bandwidth_kBps"`
			HypervisorTimespanUsecs              string `json:"hypervisor_timespan_usecs"`
			HypervisorNumWriteIops               string `json:"hypervisor_num_write_iops"`
			TotalReadIoSizeKbytes                string `json:"total_read_io_size_kbytes"`
			HypervisorTotalIoSizeKbytes          string `json:"hypervisor_total_io_size_kbytes"`
			AvgIoLatencyUsecs                    string `json:"avg_io_latency_usecs"`
			HypervisorNumReadIops                string `json:"hypervisor_num_read_iops"`
			ControllerWriteIoBandwidthKBps       string `json:"controller_write_io_bandwidth_kBps"`
			ControllerWriteIoPpm                 string `json:"controller_write_io_ppm"`
			HypervisorAvgWriteIoLatencyUsecs     string `json:"hypervisor_avg_write_io_latency_usecs"`
			HypervisorTotalReadIoSizeKbytes      string `json:"hypervisor_total_read_io_size_kbytes"`
			ReadIoBandwidthKBps                  string `json:"read_io_bandwidth_kBps"`
			HypervisorNumIops                    string `json:"hypervisor_num_iops"`
			HypervisorIoBandwidthKBps            string `json:"hypervisor_io_bandwidth_kBps"`
			ControllerNumWriteIops               string `json:"controller_num_write_iops"`
			TotalIoTimeUsecs                     string `json:"total_io_time_usecs"`
			ControllerRandomIoPpm                string `json:"controller_random_io_ppm"`
			ControllerAvgReadIoSizeKbytes        string `json:"controller_avg_read_io_size_kbytes"`
			TotalTransformedUsageBytes           string `json:"total_transformed_usage_bytes"`
			AvgWriteIoLatencyUsecs               string `json:"avg_write_io_latency_usecs"`
			NumReadIo                            string `json:"num_read_io"`
			WriteIoBandwidthKBps                 string `json:"write_io_bandwidth_kBps"`
			HypervisorReadIoBandwidthKBps        string `json:"hypervisor_read_io_bandwidth_kBps"`
			RandomIoPpm                          string `json:"random_io_ppm"`
			TotalUntransformedUsageBytes         string `json:"total_untransformed_usage_bytes"`
			HypervisorTotalIoTimeUsecs           string `json:"hypervisor_total_io_time_usecs"`
			NumRandomIo                          string `json:"num_random_io"`
			ControllerAvgWriteIoSizeKbytes       string `json:"controller_avg_write_io_size_kbytes"`
			ControllerAvgReadIoLatencyUsecs      string `json:"controller_avg_read_io_latency_usecs"`
			NumWriteIo                           string `json:"num_write_io"`
			TotalIoSizeKbytes                    string `json:"total_io_size_kbytes"`
			IoBandwidthKBps                      string `json:"io_bandwidth_kBps"`
			ControllerTimespanUsecs              string `json:"controller_timespan_usecs"`
			NumSeqIo                             string `json:"num_seq_io"`
			SeqIoPpm                             string `json:"seq_io_ppm"`
			WriteIoPpm                           string `json:"write_io_ppm"`
			ControllerAvgWriteIoLatencyUsecs     string `json:"controller_avg_write_io_latency_usecs"`
		} `json:"stats"`
		UsageStats struct {
			StorageLogicalUsageBytes string `json:"storage.logical_usage_bytes"`
			StorageCapacityBytes     string `json:"storage.capacity_bytes"`
			StorageFreeBytes         string `json:"storage.free_bytes"`
			StorageUsageBytes        string `json:"storage.usage_bytes"`
		} `json:"usage_stats"`
	} `json:"entities"`
}
