version: "3"

networks:
  proxy-net:
    driver: bridge

services:
  reverseproxy:
    container_name: nginx
    networks:
      - proxy-net
    image:  nginx:1.13.7
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  grpcclient:
    container_name: grpcclient
    networks:
      - proxy-net
    build:
      context: .
      args:
        gRPCRole: client
    ports:
      - 8001:8001
    environment:
      - GRPCADD=grpcserver

  grpcserver:
    container_name: grpcserver
    networks:
      - proxy-net
    build:
      context: .
      args:
        gRPCRole: server
    ports:
      - 50051:50051
    environment:
      - DBADD=mysql

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
     - 3306:3306
